// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFEAqw12p-OfJegiKVyd_u8zs76Hh1OQ',
    appId: '1:903314051019:web:70c9626022b40fb825f04e',
    messagingSenderId: '903314051019',
    projectId: 'ti-tan',
    authDomain: 'ti-tan.firebaseapp.com',
    storageBucket: 'ti-tan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARCnpzN4wowUqwtZqmQw_b2YqnIApRgNQ',
    appId: '1:903314051019:android:be12c5e6a543ef3025f04e',
    messagingSenderId: '903314051019',
    projectId: 'ti-tan',
    storageBucket: 'ti-tan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwxMU2noHhyj7uoHN2DjJObMp2FqMN9IE',
    appId: '1:903314051019:ios:95711c564b65649225f04e',
    messagingSenderId: '903314051019',
    projectId: 'ti-tan',
    storageBucket: 'ti-tan.appspot.com',
    iosBundleId: 'com.tytan.app.user',
  );

}