// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvjgKcScnASxGHDx4Q_78bCdJRPi5Y5xQ',
    appId: '1:33106762135:web:134107f39a2b4d05268cd2',
    messagingSenderId: '33106762135',
    projectId: 'tytan-user-a162c',
    authDomain: 'tytan-user-a162c.firebaseapp.com',
    storageBucket: 'tytan-user-a162c.appspot.com',
    measurementId: 'G-2XR4FHLYS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7Cy04VQLy3013bns7_C2FSgd-HID_Bk',
    appId: '1:33106762135:android:71a1216e79550c54268cd2',
    messagingSenderId: '33106762135',
    projectId: 'tytan-user-a162c',
    storageBucket: 'tytan-user-a162c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqZl8GlA21d0DNi3nosnjG5iuLH3_JNU',
    appId: '1:33106762135:ios:75b3fca325574424268cd2',
    messagingSenderId: '33106762135',
    projectId: 'tytan-user-a162c',
    storageBucket: 'tytan-user-a162c.appspot.com',
    iosBundleId: 'com.tytan.app.user',
  );

}